before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DvOxRNDcngfb/RUjU3KNQpJZNly1dDONKOm1NLm8wwEzqH+bDPNqVVGjH6z0lLHuATUye/WGBTGepMmG0OUrxvYAhw15alOIuaREkLuHgnVBfO27u7HXZ1OZ0V925y4J8csxpeQjXzMBMt1oWuvKo+W0eYpvpKoVa7ulsLqxQBHWCPVeXYo7v65vucsD21bj01IDyjDOd2WmMmtP+BaH9qrXGrlhpy4Kc6MrhySvzNhOc+A7eLGSNOgix1pp2Dhn2PPP3JzdN/Y2qH+WAbSMtmuNKlhYGoK/4RQFetOqcv960Qy60GASVdeEsOBkPuYXcEYfZvfPPlYP315WFyuCd4m9anpfdTW8th7Dks1ziAC7Sk20jGd4Rc8IpEOHFmbFw+d7pRZX0QnO0aeoYsl8zpQMf2NK6P75iyDLb/SwIUBdFKfWwxBdoOo4LftvXhFNQmxLUvTzFCQ8MyRWrWxR4uHagxXwQU6thDf1i6x93zKBtpyG8x9qVlOD5NppiG+FZ+aeOpQ1k0PuTSmyAiQeV8AWyjniy2loNtr2FuoDUnUqYQ/57a1zwIBYqOMTbRPrICFwxJ8Rzro0i1JukhyJznjo9SDctv2uUiGj7RvOvAFSmWgDvRwE3jFpDjK6f2VBCrNxyPSLuH41l3wyGQDO7Ofl8orheigOEV5rmHy6G6Y= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
